name: Linux

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tagname:
        description: 'tagname'
        type: string
        required: true
      pkgrel:
        description: pkgrel
        type: number
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.tagname.outputs.tagname }}
    env:
      IMAGE_TAG: materialgram:build

    steps:
      - name: Set TAGNAME
        id: tagname
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAGNAME="${{ github.event.inputs.tagname }}"
          else
            TAGNAME="${GITHUB_REF#refs/tags/}"
          fi
          echo "TAGNAME=$TAGNAME" >> $GITHUB_ENV
          echo "tagname=$TAGNAME" >> $GITHUB_OUTPUT

      - name: Clone.
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ env.TAGNAME }}

      - name: Pull Docker IMG
        run: |
          docker pull ghcr.io/telegramdesktop/tdesktop/centos_env
          docker tag ghcr.io/telegramdesktop/tdesktop/centos_env $IMAGE_TAG

      - name: materialgram build
        run: |
          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Release \
          -D TDESKTOP_API_ID=${{ secrets.API_ID }} \
          -D TDESKTOP_API_HASH=${{ secrets.API_HASH }}

      - name: Create Tar
        run: |
          cd arch
          bash setup.sh
          tar -czvf materialgram-${{ env.TAGNAME }}.tar.gz usr

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: materialgram-${{ env.TAGNAME }}
          path: arch/materialgram-${{ env.TAGNAME }}.tar.gz

      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAGNAME }}
          tag_name: ${{ env.TAGNAME }}
          token: ${{ secrets.PAT }}
          files: arch/materialgram-${{ env.TAGNAME }}.tar.gz

  trigger-workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
     
      - name: Set PKGREL & TAGNAME
        run: |
          if [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            PKGREL="${{ github.event.inputs.pkgrel }}"
          else
            PKGREL="1"
          fi
          echo "PKGREL=$PKGREL" >> $GITHUB_ENV
          echo "TAGNAME=${{ needs.build.outputs.tagname }}" >> $GITHUB_ENV

      - name: Trigger repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.OKsPAT }}
          repository: materialgram/materialgram-bin
          event-type: new-release
          client-payload: '{"tagname": "${{ env.TAGNAME }}", "pkgrel": "${{ env.PKGREL }}"}'
